# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 627)
        MainWindow.setMinimumSize(QtCore.QSize(417, 627))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 190, 395, 397))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_percent = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_percent.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_percent.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.gridLayout.addWidget(self.pushButton_percent, 0, 0, 1, 1)
        self.pushButton_sqrt = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sqrt.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_sqrt.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sqrt.setFont(font)
        self.pushButton_sqrt.setObjectName("pushButton_sqrt")
        self.gridLayout.addWidget(self.pushButton_sqrt, 0, 1, 1, 1)
        self.pushButton_pow = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_pow.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_pow.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pow.setFont(font)
        self.pushButton_pow.setObjectName("pushButton_pow")
        self.gridLayout.addWidget(self.pushButton_pow, 0, 2, 1, 1)
        self.pushButton_inverse = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_inverse.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_inverse.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_inverse.setFont(font)
        self.pushButton_inverse.setObjectName("pushButton_inverse")
        self.gridLayout.addWidget(self.pushButton_inverse, 0, 3, 1, 1)
        self.pushButton_clearEntry = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearEntry.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_clearEntry.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clearEntry.setFont(font)
        self.pushButton_clearEntry.setObjectName("pushButton_clearEntry")
        self.gridLayout.addWidget(self.pushButton_clearEntry, 1, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_clear.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 1, 1, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_delete.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 1, 2, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_div.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_div.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 1, 3, 1, 1)
        self.pushButton_num7 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num7.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num7.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num7.setFont(font)
        self.pushButton_num7.setObjectName("pushButton_num7")
        self.gridLayout.addWidget(self.pushButton_num7, 2, 0, 1, 1)
        self.pushButton_num8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num8.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num8.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num8.setFont(font)
        self.pushButton_num8.setObjectName("pushButton_num8")
        self.gridLayout.addWidget(self.pushButton_num8, 2, 1, 1, 1)
        self.pushButton_num9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num9.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num9.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num9.setFont(font)
        self.pushButton_num9.setObjectName("pushButton_num9")
        self.gridLayout.addWidget(self.pushButton_num9, 2, 2, 1, 1)
        self.pushButton_mul = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_mul.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_mul.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 2, 3, 1, 1)
        self.pushButton_num4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num4.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num4.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num4.setFont(font)
        self.pushButton_num4.setObjectName("pushButton_num4")
        self.gridLayout.addWidget(self.pushButton_num4, 3, 0, 1, 1)
        self.pushButton_num5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num5.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num5.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num5.setFont(font)
        self.pushButton_num5.setObjectName("pushButton_num5")
        self.gridLayout.addWidget(self.pushButton_num5, 3, 1, 1, 1)
        self.pushButton_num6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num6.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num6.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num6.setFont(font)
        self.pushButton_num6.setObjectName("pushButton_num6")
        self.gridLayout.addWidget(self.pushButton_num6, 3, 2, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sub.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_sub.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 3, 3, 1, 1)
        self.pushButton_num1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num1.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num1.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num1.setFont(font)
        self.pushButton_num1.setObjectName("pushButton_num1")
        self.gridLayout.addWidget(self.pushButton_num1, 4, 0, 1, 1)
        self.pushButton_num2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num2.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num2.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num2.setFont(font)
        self.pushButton_num2.setObjectName("pushButton_num2")
        self.gridLayout.addWidget(self.pushButton_num2, 4, 1, 1, 1)
        self.pushButton_num3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num3.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num3.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num3.setFont(font)
        self.pushButton_num3.setObjectName("pushButton_num3")
        self.gridLayout.addWidget(self.pushButton_num3, 4, 2, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_add.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 4, 3, 1, 1)
        self.pushButton_plusminus = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_plusminus.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_plusminus.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plusminus.setFont(font)
        self.pushButton_plusminus.setObjectName("pushButton_plusminus")
        self.gridLayout.addWidget(self.pushButton_plusminus, 5, 0, 1, 1)
        self.pushButton_num0 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_num0.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_num0.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num0.setFont(font)
        self.pushButton_num0.setObjectName("pushButton_num0")
        self.gridLayout.addWidget(self.pushButton_num0, 5, 1, 1, 1)
        self.pushButton_dot = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dot.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_dot.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout.addWidget(self.pushButton_dot, 5, 2, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_equal.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_equal.setBaseSize(QtCore.QSize(30, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.gridLayout.addWidget(self.pushButton_equal, 5, 3, 1, 1)
        self.lineEdit_display = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_display.setGeometry(QtCore.QRect(10, 50, 391, 81))
        self.lineEdit_display.setStyleSheet("font: 75 26pt \"Magneto\";")
        self.lineEdit_display.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lineEdit_display.setObjectName("lineEdit_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "계산기"))
        self.pushButton_percent.setText(_translate("MainWindow", "%"))
        self.pushButton_sqrt.setText(_translate("MainWindow", "√"))
        self.pushButton_pow.setText(_translate("MainWindow", "x²"))
        self.pushButton_inverse.setText(_translate("MainWindow", "1/x"))
        self.pushButton_clearEntry.setText(_translate("MainWindow", "CE"))
        self.pushButton_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_delete.setText(_translate("MainWindow", "←"))
        self.pushButton_div.setText(_translate("MainWindow", "÷"))
        self.pushButton_num7.setText(_translate("MainWindow", "7"))
        self.pushButton_num8.setText(_translate("MainWindow", "8"))
        self.pushButton_num9.setText(_translate("MainWindow", "9"))
        self.pushButton_mul.setText(_translate("MainWindow", "×"))
        self.pushButton_num4.setText(_translate("MainWindow", "4"))
        self.pushButton_num5.setText(_translate("MainWindow", "5"))
        self.pushButton_num6.setText(_translate("MainWindow", "6"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_num1.setText(_translate("MainWindow", "1"))
        self.pushButton_num2.setText(_translate("MainWindow", "2"))
        self.pushButton_num3.setText(_translate("MainWindow", "3"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_plusminus.setText(_translate("MainWindow", "±"))
        self.pushButton_num0.setText(_translate("MainWindow", "0"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_equal.setText(_translate("MainWindow", "="))
        self.lineEdit_display.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

