queryMemberGetColumnsName = "select COLUMN_NAME from information_schema.COLUMNS where TABLE_NAME='member'"
queryMemberGetColumnsNameNotInIndex = "select COLUMN_NAME from information_schema.COLUMNS where TABLE_NAME='member' and COLUMN_NAME != 'idx'"
queryMemberGetLastIndex = "select MAX(idx) as idx from member"
queryMemberInit = """insert into member values(%s, %s, %s, %s, %s, %s)"""
queryMemberAdd = """insert into member(ID, password, name, sex, age) values(%s, %s, %s, %s, %s)"""
queryMemberAllSelect = "select * from member"
queryMemberOneResearch = "select * from member where name = %s limit 1"
queryMemberOneResearchSpecificColumn = "select * from member where %s = %s limit 1"
queryMemberResearch = "select * from member where name = %s"
queryMemberResearchSpecificColumn = "select * from member where %s = %s"
queryMemberModify = """update member set name = %s where name = %s"""
queryMemberModifySpecificColumn = """update member set %s = %s where %s = %s"""
queryMemberMultiModify = """update member set password = %s, name = %s, age = %s where name = %s"""
queryMemberRemove = """delete from member where name = %s"""
queryMemberRemoveSpecificColumn = """delete from member where %s = %s"""